package ${template.getPackage()};

<#list template.getAllImports() as imp>
import ${imp};
</#list>

/**
 * REST Controller for {@link ${template.entity.className}} entity operations.
 * <p>
 * Provides RESTful endpoints for ${template.entity.tableName} entity management.
 * All responses use ResponseEntity for proper HTTP status handling.
 *
 * Automatically generated by EntityGen Maven Plugin
 */
@RequiredArgsConstructor
@RestController
@RequestMapping("/${template.entity.tableName?lower_case}")
public class ${template.getControllerName()} {

    private final ${template.getServiceName()} service;

    /**
     * Retrieves all entities as DTOs.
     *
     * @return ResponseEntity with list of all DTOs and HTTP 200 status
     */
    @GetMapping
    public ResponseEntity<List<${template.getDtoName()}>> findAll() {
        List<${template.getDtoName()}> entities = service.findAll();
        return entities.isEmpty()
            ? ResponseEntity.noContent().build()
            : ResponseEntity.ok(entities);
    }
}