package ${template.getPackage()};

<#list template.getAllImports() as imp>
import ${imp};
</#list>

/**
 * Embeddable class for {@link ${template.entity.className}} entity operations.
 * <p>
 * Embeddable class for composite primary key of ${template.entity.tableName} table.
 *
 * Automatically generated by EntityGen Maven Plugin
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Embeddable
public class ${template.getName()} implements Serializable {

    private static final long serialVersionUID = 1L;

    <#list template.entity.embeddedId.fields as field>
    @Column(${template.getColumnParams(field)})
    private ${field.javaType} ${field.name};
    </#list>
    
}
