package ${template.getPackage()};

<#list template.getAllImports() as imp>
import ${imp};
</#list>

/**
 * Repository interface for {@link ${template.entity.className}} entity.
 * <p>
 * Provides CRUD operations and custom queries for ${template.entity.tableName} entity.
 *
 * Automatically generated by EntityGen Maven Plugin
 */
@Repository
public interface ${template.getName()} extends JpaRepository<${template.getEntityName()}, ${template.getIdType()}> {
}