package ${template.getPackage()};

<#list template.getAllImports() as imp>
import ${imp};
</#list>

/**
 * Service implementation for {@link ${template.entity.className}} business logic.
 * <p>
 * Handles entity-to-DTO conversion and repository operations.
 *
 * Automatically generated by EntityGen Maven Plugin
 */
@Service
@RequiredArgsConstructor
public class ${template.getName()} implements ${template.getServiceName()} {

    private final ${template.getRepositoryName()} repository;

    @Override
    public List<${template.getDtoName()}> findAll() {
        return repository.findAll()
                .stream()
                .map(this::toDto)
                .toList();
    }

    /**
     * Converts entity to DTO.
     *
     * @param entity the entity to convert
     * @return converted DTO
     */
    private ${template.getDtoName()} toDto(${template.getEntityName()} entity) {
        return new ${template.getDtoName()}(
                    ${template.getDtoConstructorParams()}
        );
    }
}
