package ${template.getPackage()};

<#list template.getAllImports() as imp>
import ${imp};
</#list>

/**
 * Service interface for {@link ${template.entity.className}} business logic.
 * <p>
 * Provides high-level operations for ${template.entity.tableName} entity management.
 *
 * Automatically generated by EntityGen Maven Plugin
 */
public interface ${template.getName()} {
    
    /**
     * Retrieves all entities as DTOs.
     *
     * @return list of all entities converted to DTOs
     */
    List<${template.getDtoName()}> findAll();
}