package ${template.componentPackage};

<#list template.imports as imp>
${imp}
</#list>

/**
 * Service implementation for {@link ${template.userConfig.entityPackage}.${template.entity.className}} business logic.
 * <p>
 * Handles entity-to-DTO conversion and repository operations.
 *
 * Automatically generated by EntityGen Maven Plugin
 */
@Service
@RequiredArgsConstructor
public class ${template.serviceImplName} implements ${template.serviceName} {

    private final ${template.repositoryName} repository;

    @Override
    public List<${template.dtoName}> findAll() {
        return repository.findAll()
                .stream()
                .map(this::toDto)
                .toList();
    }

    /**
     * Converts entity to DTO.
     *
     * @param entity the entity to convert
     * @return converted DTO
     */
    private ${template.dtoName} toDto(${template.entityName} entity) {
        return new ${template.dtoName}(
                ${template.modelBody}
        );
    }

}
